import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useEffect, useRef, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [products, setProducts] = useState<
    { id: string; properties: { id: string }[] }[]
  >([])
  useEffect(() => {
    fetch('/api/get-items')
      .then((res) => res.json())
      .then((data) => setProducts(data.items))
  }, [])
  const inputRef = useRef<HTMLInputElement>(null)
  const handleClick = () => {
    if (inputRef.current == null || inputRef.current.value == '') {
      alert('name값이 없습니다')
      return
    }
    fetch(`/api/add-item?name=${inputRef.current.value}`)
      .then((res) => res.json())
      .then((data) => alert(data.message))
  }
  return (
    <>
      <Head>
        <title>넥스트 쇼핑 페이지</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>

          <input ref={inputRef} type="text" placeholder="name" />
          <button onClick={handleClick}>Add Jacket</button>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div>
          <p>Product List</p>
          {products &&
            products.map((item) => {
              return (
                <div key={item.id}>
                  {JSON.stringify(item)}
                  {item.properties &&
                    Object.entries(item.properties).map(([key, value]) => {
                      return (
                        <button
                          key={key}
                          onClick={() => {
                            fetch(
                              `/api/get-detail?pageId=${item.id}&propertyId=${value.id}`
                            )
                              .then((res) => res.json())
                              .then((data) =>
                                alert(JSON.stringify(data.detail))
                              )
                          }}
                        >
                          {key}
                        </button>
                      )
                    })}
                  <br />
                  <br />
                </div>
              )
            })}
        </div>
      </main>
    </>
  )
}
